import Foundation
import FoundationModels

// MARK: - Structured Output

/// Structured feedback generated by local Apple Intelligence (Foundation Models).
@Generable
struct SessionFeedback {
    /// Specific observation on what went well during this session.
    @Guide(description: "One short sentence describing a specific positive aspect — consistency, posture hold, effort. Concise and non-generic.")
    var whatWentWell: String

    /// Practical, actionable tip for the next session.
    @Guide(description: "One short, practical tip for improvement — posture alignment, breathing, or control. No clinical jargon.")
    var tipToImprove: String

    /// Brief motivational closing sentence.
    @Guide(description: "A warm, encouraging sentence under 12 words. E.g., 'Each session brings you closer to a stronger lower back.'")
    var encouragement: String
}

// MARK: - Service

/// Coaching service powered by Apple Intelligence (Foundation Models framework).
struct CoachingService {

    // MARK: - Public API

    /// Generates personalized feedback for a completed exercise session.
    static func generateFeedback(
        for record: SessionRecord,
        exerciseName: String,
        stats: [ExerciseSessionController.RuleFeedbackStat] = []
    ) async -> SessionFeedback {
        guard case .available = SystemLanguageModel.default.availability else {
            return fallback(for: record, stats: stats)
        }

        let prompt = buildPrompt(for: record, exerciseName: exerciseName, stats: stats)

        do {
            let session = LanguageModelSession()
            let response = try await session.respond(to: prompt, generating: SessionFeedback.self)
            return response.content
        } catch {
            return fallback(for: record, stats: stats)
        }
    }

    // MARK: - Private Helpers

    private static func buildPrompt(
        for record: SessionRecord,
        exerciseName: String,
        stats: [ExerciseSessionController.RuleFeedbackStat]
    ) -> String {
        let precision = Int(record.withinRangePercentage.rounded())
        let achieved  = Int(record.holdDurationAchieved.rounded())
        let target    = Int(record.targetHoldDuration.rounded())
        let quality   = qualityLabel(precision: precision, achieved: achieved, target: target)

        let movementSection: String
        if stats.isEmpty {
            movementSection = ""
        } else {
            let lines = stats.map { stat -> String in
                let percentOfTarget = stat.requiredDelta > 0
                    ? Int((stat.averageDeltaAchieved / stat.requiredDelta * 100).rounded())
                    : 100
                return "- \(stat.movementLabel): averaged \(String(format: "%.0f", stat.averageDeltaAchieved))° of motion (target was \(String(format: "%.0f", stat.requiredDelta))°, \(percentOfTarget)% of target), best moment reached \(String(format: "%.0f", stat.maxDeltaAchieved))°"
            }.joined(separator: "\n")
            movementSection = """


            MOVEMENT DETAIL (measured this session, per body movement tracked):
            \(lines)

            Reference the specific movement(s) above by name in your feedback — name the
            body part or movement (e.g. "spine arch", "torso rotation"), not just a
            generic "posture" or "accuracy" percentage. If a movement fell short of its
            target, mention it by name in the tip. If it met or exceeded target, mention
            that specifically in what went well.
            """
        }

        return """
        You are a supportive physical wellness coach specializing in lower back health.
        Analyze the exercise session below and provide personalized, encouraging feedback.

        STRICT RULES:
        - Write in English only
        - Do NOT use emojis
        - Tone: warm, positive, supportive — like an experienced physical wellness coach
        - Keep sentences short (maximum 20 words per field)
        - Avoid clinical or medical jargon
        - Be specific: reference actual body parts/movements from MOVEMENT DETAIL when available, not generic posture language

        SESSION DATA:
        Exercise: \(exerciseName)
        Posture accuracy: \(precision)%
        Hold time achieved: \(achieved)s out of \(target)s target
        Overall quality: \(quality)\(movementSection)
        """
    }

    private static func qualityLabel(precision: Int, achieved: Int, target: Int) -> String {
        let holdRatio = target > 0 ? Double(achieved) / Double(target) : 0
        switch (precision, holdRatio) {
        case (80..., 0.9...):
            return "Excellent — posture maintained with high accuracy for almost the entire duration"
        case (60..., 0.7...):
            return "Good — solid posture with minor adjustments"
        case (40..., 0.5...):
            return "Moderate — some difficulty maintaining alignment over longer holds"
        default:
            return "Getting started — challenging session, but effort builds progress"
        }
    }

    private static func fallback(
        for record: SessionRecord,
        stats: [ExerciseSessionController.RuleFeedbackStat]
    ) -> SessionFeedback {
        let precision = Int(record.withinRangePercentage.rounded())

        let whatWentWell: String
        if let strongest = stats.max(by: { relativePerformance($0) < relativePerformance($1) }) {
            whatWentWell = relativePerformance(strongest) >= 1.0
                ? "Your \(strongest.movementLabel) averaged \(Int(strongest.averageDeltaAchieved.rounded()))°, meeting the \(Int(strongest.requiredDelta.rounded()))° target."
                : "Your best \(strongest.movementLabel) reached \(Int(strongest.maxDeltaAchieved.rounded()))°, working toward the \(Int(strongest.requiredDelta.rounded()))° target."
        } else {
            switch precision {
            case 80...: whatWentWell = "You maintained excellent posture throughout the hold."
            case 60...: whatWentWell = "You completed all repetitions with consistent effort."
            default: whatWentWell = "You completed the session even when it felt challenging."
            }
        }

        let tipToImprove: String
        if let weakest = stats.min(by: { relativePerformance($0) < relativePerformance($1) }),
           relativePerformance(weakest) < 1.0 {
            tipToImprove = "Try deepening your \(weakest.movementLabel) further — you averaged \(Int(weakest.averageDeltaAchieved.rounded()))° of the \(Int(weakest.requiredDelta.rounded()))° needed."
        } else if !stats.isEmpty {
            tipToImprove = "Great range of motion — try holding a touch longer next time."
        } else {
            switch precision {
            case 80...: tipToImprove = "Try increasing your hold duration by 5 seconds next time."
            case 60...: tipToImprove = "Focus on slow, steady breathing to stay steady during the hold."
            default: tipToImprove = "Start with smaller movements and build up your range gradually."
            }
        }

        return SessionFeedback(
            whatWentWell: whatWentWell,
            tipToImprove: tipToImprove,
            encouragement: "Session complete! Every step builds long-term back health."
        )
    }

    /// Razão entre a variação média alcançada e a exigida — usada para
    /// identificar o movimento mais forte/mais fraco da sessão no fallback.
    private static func relativePerformance(_ stat: ExerciseSessionController.RuleFeedbackStat) -> Double {
        stat.requiredDelta > 0 ? stat.averageDeltaAchieved / stat.requiredDelta : 1
    }
}
