import Foundation
import FoundationModels

// MARK: - Structured Output

/// Structured feedback generated by local Apple Intelligence (Foundation Models).
@Generable
struct SessionFeedback {
    /// Specific observation on what went well during this session.
    @Guide(description: "One short sentence describing a specific positive aspect — consistency, posture hold, effort. Concise and non-generic.")
    var whatWentWell: String

    /// Practical, actionable tip for the next session.
    @Guide(description: "One short, practical tip for improvement — posture alignment, breathing, or control. No clinical jargon.")
    var tipToImprove: String

    /// Brief motivational closing sentence.
    @Guide(description: "A warm, encouraging sentence under 12 words. E.g., 'Each session brings you closer to a stronger lower back.'")
    var encouragement: String
}

// MARK: - Service

/// Coaching service powered by Apple Intelligence (Foundation Models framework).
struct CoachingService {

    // MARK: - Public API

    /// Generates personalized feedback for a completed exercise session.
    static func generateFeedback(
        for record: SessionRecord,
        exerciseName: String
    ) async -> SessionFeedback {
        guard case .available = SystemLanguageModel.default.availability else {
            return fallback(for: record)
        }

        let prompt = buildPrompt(for: record, exerciseName: exerciseName)

        do {
            let session = LanguageModelSession()
            let response = try await session.respond(to: prompt, generating: SessionFeedback.self)
            return response.content
        } catch {
            return fallback(for: record)
        }
    }

    // MARK: - Private Helpers

    private static func buildPrompt(for record: SessionRecord, exerciseName: String) -> String {
        let precision = Int(record.withinRangePercentage.rounded())
        let achieved  = Int(record.holdDurationAchieved.rounded())
        let target    = Int(record.targetHoldDuration.rounded())
        let quality   = qualityLabel(precision: precision, achieved: achieved, target: target)

        return """
        You are a supportive physical wellness coach specializing in lower back health.
        Analyze the exercise session below and provide personalized, encouraging feedback.

        STRICT RULES:
        - Write in English only
        - Do NOT use emojis
        - Tone: warm, positive, supportive — like an experienced physical wellness coach
        - Keep sentences short (maximum 20 words per field)
        - Avoid clinical or medical jargon

        SESSION DATA:
        Exercise: \(exerciseName)
        Posture accuracy: \(precision)%
        Hold time achieved: \(achieved)s out of \(target)s target
        Overall quality: \(quality)
        """
    }

    private static func qualityLabel(precision: Int, achieved: Int, target: Int) -> String {
        let holdRatio = target > 0 ? Double(achieved) / Double(target) : 0
        switch (precision, holdRatio) {
        case (80..., 0.9...):
            return "Excellent — posture maintained with high accuracy for almost the entire duration"
        case (60..., 0.7...):
            return "Good — solid posture with minor adjustments"
        case (40..., 0.5...):
            return "Moderate — some difficulty maintaining alignment over longer holds"
        default:
            return "Getting started — challenging session, but effort builds progress"
        }
    }

    private static func fallback(for record: SessionRecord) -> SessionFeedback {
        let precision = Int(record.withinRangePercentage.rounded())

        let whatWentWell: String
        let tipToImprove: String

        switch precision {
        case 80...:
            whatWentWell = "You maintained excellent posture throughout the hold."
            tipToImprove = "Try increasing your hold duration by 5 seconds next time."
        case 60...:
            whatWentWell = "You completed all repetitions with consistent effort."
            tipToImprove = "Focus on slow, steady breathing to stay steady during the hold."
        default:
            whatWentWell = "You completed the session even when it felt challenging."
            tipToImprove = "Start with smaller movements and build up your range gradually."
        }

        return SessionFeedback(
            whatWentWell: whatWentWell,
            tipToImprove: tipToImprove,
            encouragement: "Session complete! Every step builds long-term back health."
        )
    }
}
